CREATE TABLE DBAHawk.SavedViews(
	SavedViewID INT IDENTITY(1,1) CONSTRAINT PK_DBADash_SavedViews PRIMARY KEY,
	UserID INT NOT NULL REFERENCES DBAHawk.Users(UserID),
	Name NVARCHAR(50) NOT NULL,
	ViewType TINYINT NOT NULL REFERENCES DBAHawk.ViewType(ViewTypeID),
	SavedObject NVARCHAR(MAX) NOT NULL,
	CreatedDate DATETIME2(2) NOT NULL CONSTRAINT DF_DBADash_SavedViews_CreatedDate DEFAULT(SYSUTCDATETIME()),
	ModifiedDate DATETIME2(2) NOT NULL CONSTRAINT DF_DBADash_SavedViews_ModifiedDate DEFAULT(SYSUTCDATETIME())
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_DBADash_SavedViews_UserID_ViewType_Name ON DBAHawk.SavedViews(UserID,ViewType,Name)